version: '3'

services:
  delay-server:
    container_name: my-site
    image: winterchen/my-site
    ports:
      - "8089:8089"
    volumes:
      - "./log:/log"
    environment:
      SPRING_DATASOURCE_DRUID_URL: jdbc:mysql://127.0.0.1:3306/lu_tale?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      SPRING_DATASOURCE_DRUID_USERNAME: root
      SPRING_DATASOURCE_DRUID_PASSWORD: root
      QINIU_ACCESSKEY: "y8FqF0iKXzd4QPuhKK_ZQprvEa9fAVtQUIv0Rk_7"
      QINIU_SERECTKEY: "o93m3PmhrSywi8C1Rn60fBE_F_rda5Jjv0avIAB0"
      QINIU_BUCKET: "deerspace"
      QINIU_CDN_URL: "r9fxwez6s.hb-bkt.clouddn.com"